# Generated by Django 5.0.1 on 2024-02-07 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyperAPIs', '0002_alter_users_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='username',
        ),
    ]
