# Generated by Django 5.0.1 on 2024-02-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyperAPIs', '0003_rename_name_users_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
